### ISSUE TITLE
Missing tag values always treated as empty

### ISSUE THREAD

**Issue by richardhills** [defunkt/pystache#110]
It would be great (as apparently is the case in the Ruby moustache version) to have the option of errors generated when tags are missing.

In fact, since pystache uses hasattr to check for tags, this can cause errors to be lost if the tag is returned from a property function. Any exceptions generated by property functions are swallowed and pystache treats the tag as being unset.

**Comment by cjerdonek** [comment]
Thanks.  Yes, I agree.  Thanks also for the point re: `hasattr`.  Related to this, I think we should start using the [EAFP approach](http://docs.python.org/glossary.html#term-eafp) more, which would translate in this case into not needing to use `hasattr`.

**Comment by richardhills** [comment]
Good stuff. In our case, our tags are generated programmatically (for localisation), and this tag creation occasionally fails. On failure, we currently have no mechanism for terminating the templating, as any exceptions thrown are swallowed, and the resulting output is bad.

I'd much rather that templating fails with an exception, instead of generating bad output.

**Comment by cjerdonek** [comment]
I'm thinking something like a "strict mode" on the `Renderer`.

**Comment by richardhills** [comment]
That sounds ideal.

**Comment by cjerdonek** [comment]
Note for when implementing: Pystache should also raise an error when a partial is not found -- even after addressing issue #115.

**Comment by cjerdonek** [comment]
@richardhills, I just addressed the second issue you mentioned re: exceptions raised from properties.  I'll address the other issue re: missing tags in a separate commit.

Note that my resolution of the first issue needs a little more work in order to distinguish missing attributes from properties that raise an `AttributeError` (as opposed to any other exception type), but what I've done should take care of the bulk of real-world cases.  Making the additional distinction is a bit trickier, but I believe it can be done (see my `TODO` in the code comments).  We'll see if the additional distinction is worth the extra cost once it's implemented.

**Comment by richardhills** [comment]
@cjerdonek, thanks for this, I think this covers our most important use case. I have a feeling you can't distinguish between properties that raise AttributeError from missing attributes in python (even hasattr checks for that exception, so can not distinguish). Instead, I would treat these two cases (missing attributes and throwing AttributeError) as the same thing, but then have a "strict" mode on the renderer which then decides to rethrow or swallow.

Anyway, thanks for making these changes - it's really appreciated.

**Comment by cjerdonek** [comment]
I think it may be possible to distinguish those cases by walking and inspecting the stack, because the stack trace will have slightly different characteristics in the two cases.  For example--

```
>>> class Foo(object):
...   @property
...   def bar(self):
...     raise AttributeError("test")
... 
>>> foo = Foo()
>>> foo.bar()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 4, in bar
AttributeError: test
>>> foo.baz()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'Foo' object has no attribute 'baz'
```

The idea of inspecting the stack was mentioned by Michael Foord in the Python [issue thread](http://bugs.python.org/issue7559) I linked to in [my code comment](https://github.com/defunkt/pystache/commit/d9554ae27d2468b7f03acdcb59ee1bd020abde3e#L1R61).  The thread points people [here](http://twistedmatrix.com/trac/browser/trunk/twisted/python/reflect.py#L426) for an example of this type of approach (walking the stack).  But yes, I agree this case is low priority.

And sure thing, you're welcome. :)  I should be done with the strict mode shortly.

**Comment by cjerdonek** [comment]
I merged the changes for this issue into the development branch.

Let me know if you see anything with this that isn't right or that you think can be improved.  Thanks.
