### ISSUE TITLE
Documentation needed: how to specify a template path?

### ISSUE THREAD

**Issue by eykd** [defunkt/pystache#111]
I found Pystache via http://duganchen.ca/single-page-web-app-architecture-done-right/ which uses this declaration to specify a template path:

```
pystache.View.template_path = settings.MEDIA_ROOT
```

With the move to 0.5.0 and the removal of the View class, this of course no longer works. The examples mix `*.py` and `*.mustache` files in the same folder, but I need to put my templates in a separate folder. The documentation for the library should specify how to do this.

Thanks!

**Comment by eykd** [comment]
My initial grep for `template_path` didn't turn anything up, but upon reading through the code and docstrings, I see that instantiating the Renderer with a `search_dirs` keyword argument may do what I'm looking for. However, this is a basic enough setting, it would be nice to have in the README example.

**Comment by cjerdonek** [comment]
Hi @eykd, thanks for the report. And thanks for your patience with the switch to 0.5.0. I'm glad you found the `search_dirs` argument.

Another option, if you would like to customize the search directory on a per-view basis, is to subclass the [`TemplateSpec`](https://github.com/defunkt/pystache/blob/master/pystache/template_spec.py) class and set attributes there as appropriate.  In some sense, the `TemplateSpec` class succeeds the `View` class, but without any need for code (it's a dumbed-down class).

Test coverage around the `TemplateSpec` class isn't complete for all attributes, so let me know if you experience any issues there.  Also, I would still like to add "absolute" versions of some of those attributes so that paths don't always need to be specified relatively.

Regarding documentation, it's tricky because there's a lot of extra stuff that's spelled out in the docstrings, and Chris's original style was to keep the README bare bones.  So it's hard to know where to draw the line.  Perhaps simply a couple pointers to where to look in the code for the main docstrings would suffice.  I will think about this.  Thanks again.

**Comment by cjerdonek** [comment]
Thinking about this a little bit more, I'll start by adding a couple sentences at the end of the "Use It" section saying that attributes can be passed in or set on the `Renderer` to customize rendering behavior, and that views can subclass `TemplateSpec` for per-view customizations.  And then refer them to the class docstrings.

**Comment by eykd** [comment]
Honestly, I really don't like the magically-named subclass approach (or maybe I just don't get it), but I'll try to spare you my bike-shedding. Perhaps `pystache.render()` could use a default `pystache.default_renderer` object, instead of instantiating a new one each time? Then one could simply do `pystache.default_renderer.search_dirs.append(MY_TEMPLATE_PATH)`.

Crafting a good README strikes me as a tricky feat: you want to avoid too long and too short. The current README could definitely use a few "see also" pointers.

**Comment by cjerdonek** [comment]
There are a couple reasons for the magic subclass.  The first is that it shouldn't be a requirement for the end-user to do anything special to create a view.  It's not necessary in many cases.  It just needs to be an instance.  The second is that it allows at least some users to be insulated from possible collisions between tag names and attributes on the subclass.

At some point there will have to be something "magical" to distinguish ordinary views from customizable views, whether that be via a magic attribute, subclass, etc.  I don't view it as a big deal right now because it would be easy to change.  Maybe it can be a single property on the user's view called something like `__pystache__` whose value is an object with all the special customizations as attributes.  The user would be free to set that, but only if they want.  This is a separate issue from the documentation stuff though.

The stuff about `pystache.render()` is also a separate issue.  For anything more than examples and testing, I'd recommend that  users instantiate `Renderer` instances directly.  Otherwise, more of the `Renderer` API would need to be exposed a second time via `pystache.render()`.

Feel free to file an issue if you see any other places in the README where an additional pointer would be helpful.

**Comment by cjerdonek** [comment]
Addressed in the development branch
