### ISSUE TITLE
Add Python 3 manual installation instructions to README

### ISSUE THREAD

**Issue by ghost** [defunkt/pystache#112]
After a manual install with `setup.py build` and `setup.py install`, an "import pystache" fails with the following error :

<pre>
  File "pystache\renderer.py", line 26
    _STRING_TYPES = (unicode, type(u"a".encode('utf-8')))
                                      ^
SyntaxError: invalid syntax
</pre>

The sources files in the site-packages folder does not match the compiled versions.
Doing a `cp -r build/lib/pystache/* pystache/` in the source root directory and relaunching `setup.py install` did the trick.

**Comment by cjerdonek** [comment]
Thanks for the report.  I was able to reproduce this on Mac OS X, so I'm going to edit the title accordingly.

It looks like the issue might be that the directory for the original Python 2 source code is in your `sys.path` before the site-packages directory, so it winds up trying to import the Python 2 source code.  I was able to `import pystache` if I either (1) removed `''` from `sys.path` prior to importing (because Python adds the current working directory to `sys.path` when running the IDE), or (2) changing directories out of the project directory before running the IDE.

This might best be solved via documentation in the README (i.e. don't run the IDE from the project directory when using Python 3).  I'll think about this a little and maybe ask around.

**Comment by cjerdonek** [comment]
Also @kbok, can you clarify whether the Pystache source in your site-packages directory looks okay?  In your comment, you say you copied over the `pystache` directory (which I assume is a subdirectory of the project directory), but you didn't change site-packages at all.

**Comment by ghost** [comment]
Yes, the source looks fine (before and after the workaround). I had a look at the source file in `C:\Python32\Lib\site-packages\pystache-0.5.1_rc-py3.2.egg\pystache` and the erroneous line was actually different (`STRING_TYPES = (str, type("a".encode('utf-8')))`) so I suppose the build gets mangled and the module ends up with different versions for the source and the pyc files ?

Also, I think relaunching `setup.py install` is what updated the site-packages directory.

**Comment by cjerdonek** [comment]
> so I suppose the build gets mangled and the module ends up with different versions for the source and the pyc files ?

No, here is what is happening so you can understand.  The source code on GitHub is written in Python 2, so you will get the above `SyntaxError` if you try to import it using Python 3.

As far as installing, etc, there are three locations of interest: (1) the original source code directory, (2) the build subdirectory of the source code directory, and (3) your system's site-packages directory.

The original source code directory is Python 2.  Running `setup.py build` copies the code to the build directory and converts it to Python 3 (leaving the original Python 2 code alone).  Running `setup.py install` copies the Python 3 code from the build directory to your site-packages directory (again, leaving the original Python 2 code alone).

When you tried importing pystache above, you were trying to import the original Python 2 source code.  It wasn't even looking in site-packages.  The code in site-packages was always Python 3.  When you copied the contents of the build directory to your original source code location, you overwrote the Python 2 code with the Python 3 code, which made it work.  In the future, whenever you run your IDE, first `cd` out of the project directory so that when you run `import pystache`, it won't look first at the original Python 2 source code and will instead look in the site-packages directory like it is supposed to.

I will try to add a note about this to the `README` to prevent other people from having this same problem.

**Comment by cjerdonek** [comment]
Also, I verified on a Windows machine with Python 3.2 that the situation above is as I described.

**Comment by cjerdonek** [comment]
I added a couple paragraphs to the end of the "Develop" section of the [README](https://github.com/defunkt/pystache/blob/72ec1c961467aeda5cebe5854d96e165ed2dd758/README.rst) (in a section called "Running Pystache from source with Python 3.") to address this issue.
