### ISSUE TITLE
template_rel_directory doesn't filter through to {{>partial}} name search

### ISSUE THREAD

**Issue by ahri** [defunkt/pystache#129]
Specifying:

```
class PublicTemplate(TemplateSpec):

    template_rel_directory = 'static/templates'
```

Still requires a partial to be specified as:

```
{{> static/templates/header}}
```

which seems like a bug?

**Comment by cjerdonek** [comment]
Thanks for the report.   I'm not sure `template_rel_directory` should be used in that way.  Can you say more about what you're trying to do?  The `template_rel_directory` attribute was designed to be used for locating the template file corresponding to a "view" class, rather than for locating the template files of partials that a view class's template string references.  Would it work for you to add the directory containing the partial to the `search_dirs` list?

Incidentally, I'm surprised that including a path as the partial name works.  I'm not sure that's a supported use case.

**Comment by ahri** [comment]
Yeah I wasn't sure it would work but had a go and was surprised that the paths worked in the template!

I began looking into search_dirs but wasn't sure whether I should be adding to that myself, or whether template_rel_directory should be added to search_dirs automatically.

I'm interested in how I should be doing this from your perspective: where should I add to search_dirs? Should I be specifying template_rel_directory at all?

I came across this after bringing my library up to date with your removal of Views, so I'm definitely interested in "the right way to do this" :)

**Comment by ahri** [comment]
Sorry, I didn't explain what I'm trying to do;

I have my templates in a directory (static/templates relative to my script) and I want to be able to tie a single mustache template to a class, and for that template to refer to other mustache templates in the same directory without further work.

The search_dir probably accomplishes this, but as I say; I don't understand whether I should use this (but am quite happy to).

**Comment by cjerdonek** [comment]
Thanks for asking.  For starters, I would recommend not subclassing your view classes from what is now called the `TemplateSpec` class, if you can at all avoid it.  In most cases, you shouldn't need to use the special attributes that class provides.  It is more for if you have a particular view class that is different from all the others and needs to be special-cased in some way.  Can you possibly point me to one of your view classes to have a look?

The right way to do things is to do all of your rendering by instantiating a [`Renderer`](https://github.com/defunkt/pystache/blob/master/pystache/renderer.py#L30) class.  You can pass in a number of options there.  One of those options is the `search_dirs` argument which is a list of all directories in which to look for templates (including partials).

**Comment by cjerdonek** [comment]
I would try adding "static/templates" to `search_dirs` and try making your template classes inherit from `object` instead of `TemplateSpec` (or at least not from `TemplateSpec` if you are inheriting from some other subclass for a different purpose).

**Comment by ahri** [comment]
It sounds like I should definitely go down the Renderer route then. An example of what I'm doing is the [current README](https://github.com/ahri/flask-mustache/blob/0e7f70d2c054c7f2c7a3f430640419966c209c96/README) for my project.

**Comment by cjerdonek** [comment]
Yes, the `Renderer` class will give you a lot more flexibility than the simple `render()` function.

I looked at your examples and did want to point out, though, that if you are accessing the template string as an attribute rather than as a separate file, you will need to inherit from `TemplateSpec`.  Otherwise, you probably won't need to.

**Comment by ahri** [comment]
I came across this whilst adding my unit tests, so I'll continue to inherit from TemplateSpec for those examples (as it's easier, for now!) I've updated my code to allow passing of custom Renderers so this should resolve my issue.

Thanks a lot for your help and advice.

**Comment by cjerdonek** [comment]
You're welcome, @ahri.  Good luck, and let us know if you need any other help.
