### ISSUE TITLE
Associate renderer with loader

### ISSUE THREAD

**Issue by miracle2k** [defunkt/pystache#153]
I need to manually use a loader object. It appears I need to use the following code to make partials work:

```
    self.loader = pystache.loader.Loader(
        extension='txt', search_dirs=search_dirs, file_encoding='utf-8')
    self.mustache = pystache.Renderer(
        file_extension='txt', search_dirs=search_dirs, file_encoding='utf-8')
```

That is a lot of duplicaton. I feel like I should be able to say:

```
  mustache = pystache.Renderer(loader=loader)
```

**Comment by cjerdonek** [comment]
What version of Pystache are you using?  Also, how would your code change with what's in the development branch?  It doesn't seem like your sample code would work with what's there.

**Comment by miracle2k** [comment]
I'm using 0.5.3, the most recent release. Why do you believe it wouldn't work with the dev branch? Looking over the code it would appear fine to me.

**Comment by cjerdonek** [comment]
I misread and thought you wanted to set the `loader` attribute on a renderer.  Something like--

```
renderer.loader = pystache.loader.Loader(extension='txt',
                                         search_dirs=search_dirs,
                                         file_encoding='utf-8')
```

(That's what won't work in the development branch, and maybe also in other versions.)  To make things DRY, it seems like a better way to go might be as follows:

```
renderer = pystache.Renderer(file_extension='txt',
                             search_dirs=search_dirs,
                             file_encoding='utf-8')
self.loader = renderer.make_loader()
```

The existing code is almost there -- only that the `_make_loader` method on the `Renderer` class is "private" instead of "public."  Would something like that work for you?

**Comment by miracle2k** [comment]
Well yes, that would have been my suggestion: Modify `Renderer._make_loader` to return `self.loader` if provided by the user, and only construct a renderer of it's own if there is none set.

Your approach would work as well, but I find it strange, API-wise. The Renderer component clearly has a dependency on the Loader, not the other way around, so why forcably channel the loader creation through the renderer? What if I want to modify the loader further beyond the Renderer.**init** arguments? What if I want to use a custom Loader subclass, etc.

**Comment by miracle2k** [comment]
In other words, #154 is what I was thinking about.

**Comment by cjerdonek** [comment]
> What if I want to use a custom Loader subclass, etc.

Okay, but that's not something you mentioned in your original post.  I was responding to what you wrote, which was to reduce the duplication.  What is your use case, by the way?

**Comment by miracle2k** [comment]
I need the loader to manually open templates without rendering them. My instinct was to create a Loader instance and work based on that.

Getting the Loader via renderer.make_loader() works too, it just seems a lot less natural to me.

**Comment by cjerdonek** [comment]
Let me explain some reasons why I lean against letting the user set a loader instance.

Letting a loader be set makes the API harder to understand because it becomes less clear what the `search_dirs`, `file_encoding`, etc. attributes do.  If a loader is set, are those attributes ignored, or does the loader look at them?  Also, would setting one of them modify the loader?  If they are ignored, you start getting into a situation where some arguments or attributes "turn off" others which gets combinatorially messy if others are added.  Also, what if one of those attributes is later needed by the Renderer for something other than the Loader.  Will they then both need to be passed (creating duplication that this feature was meant to avoid), or would the Renderer instead look at the Loader for the attribute?

It's true that Renderers depend on Loaders, but I think it's better to view the loader as an implementation detail.  That's why the Renderer is responsible for constructing the loader.

If the user needs a custom loader, I'm open to letting the user tell the Renderer what Loader class to use.  There haven't been any requests for this though, so I don't know what the use cases are.  I also don't know if there are any use cases for letting the user set a concrete Loader _instance_ as opposed to just the class.  If it's necessary to let the user set an instance, perhaps we could let the user subclass Renderer and override a `make_loader` method.  Such a method could look at the `search_dirs`, `file_encoding` attributes, etc. to avoid the duplication of attributes I described in the second paragraph above.

By the way, have you seen the [`load_template`](https://github.com/defunkt/pystache/blob/development/pystache/renderer.py#L339) method on the Renderer class?  Maybe that existing method is enough for your use case of "manually open[ing] templates without rendering them."

**Comment by miracle2k** [comment]
If the Loader is to be viewed as an implementation detail as opposed to be public API, then it makes perfect sense. I just assumed that I was supposed to construct a Loader manually if I wanted full control, and that the loader that was built into the renderer was only intended as a shortcut.

I missed the load_template method. It's exactly what I need. Thanks!

**Comment by cjerdonek** [comment]
Cool, glad that works for you!  And thanks for your understanding!
