### ISSUE TITLE
custom delimeter in sections do not work

### ISSUE THREAD

**Issue by gabor** [defunkt/pystache#20]
this does not work:
    >>> pystache.render('{{=[[ ]]=}} hi [[#person]]person[[/person]]',{'person':'jack'})
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "pystache/**init**.py", line 7, in render
        return Template(template, context).render()
      File "pystache/template.py", line 57, in render
        result = self.render_tags(template, context)
      File "pystache/template.py", line 113, in render_tags
        func = modifiers[tag_type]
    KeyError: '#'

**Comment by pvande** [comment]
This is because pystache attempts to parse out Inverse / Section tags before it ever attempts to parse any other tag type.

For a concrete set of tests for this and similar edge-case behaviors, check out the [official spec](https://github.com/mustache/spec).

For a (lightweight) example parser, I humbly suggest the pattern used in [Milk](https://github.com/pvande/Milk).

**Comment by kevincarrogan** [comment]
Thanks pvande.

I've definitely come across some of the edge cases which have been fixed but looking forward (or not as the case may be) to plugging in the tests in the spec to see what needs fixing.

I may put in a "hackier" fix to get the delimiter change working and then think about making a Python implementation similar to Milk.

**Comment by cjerdonek** [comment]
This is now fixed in the development branch -- after merging @pvande's parsing code.

Also, the spec tests now run as part of the unit tests.  I'll close this issue after adding an explicit test case (for those who don't pull down the spec submodule).
