### ISSUE TITLE
ur"" is not valid in Python 3

### ISSUE THREAD

**Issue by berndhahnebach** [defunkt/pystache#208]
`NON_BLANK_RE = re.compile(ur'^(.)', re.M)`

https://github.com/defunkt/pystache/blob/17a5dfdcd56eb76af731d141de395a7632a905b8/pystache/parser.py#L15

see 

https://stackoverflow.com/questions/27482273/invalid-syntax-using-regular-expression-in-python-3-4

**Comment by kerrickstaley** [comment]
@berndhahnebach you need to run the `2to3` code on the pystache code when installing it in a Python 3 environment. This is done automatically if you install pystache the normal way, using `pip`. Also, this issue is a duplicate of https://github.com/defunkt/pystache/issues/181; there is more context there.

I'd recommend closing this issue.

**Comment by berndhahnebach** [comment]
thanks for the information.
