### ISSUE TITLE
maintainers?

### ISSUE THREAD

**Issue by cjerdonek** [defunkt/pystache#38]
Is anyone actively maintaining this repo anymore?  How do we go about reviving it?

**Comment by defunkt** [comment]
I recently added @io41 as a contributor and would be happy to add anyone else who wants to hack on Pystache.

**Comment by cjerdonek** [comment]
Thanks for replying so promptly.  I would like to be added.

**Comment by io41** [comment]
@cjerdonek, I've only been added added a few days ago and have been looking over the various branches and forks around. I'm hoping to get a better overview of all that's going on around pystache before accepting pull requests and tackling the current open issues.
There's been a fair few commits regarding tidying up code, adding comments, PEP8 corrections, most which are outstanding in pull requests. I have every intention to start accepting the current open pull requests in the next week or two. Since you're interested in maintaining it too, perhaps we should start a pystache mailing list? That might be more suited than discussions via github issues. Thoughts?

**Comment by cjerdonek** [comment]
@io41, thanks for the reply.  I agree with your approach.  A mailing list sounds like a great idea and would be a good place to get agreement on the direction of things, etc.  Over time I also think it would be helpful for some of us to familiarize ourselves with the Ruby version to see how it compares with pystache in terms of features and compliance, etc.  At a glance, it seems to be a bit more mature (perhaps in part because of @defunkt's involvement).

**Comment by io41** [comment]
I was thinking the same. Another implementation I've been meaning to take a closer look at is @janl's https://github.com/janl/mustache.js/.

I've created the mailing list: pystache@librelist.com

**Comment by defunkt** [comment]
@pvande is the driving force these days. He oversees https://github.com/mustache/spec

**Comment by io41** [comment]
Afaik @carlmw wrote test code for the specs in https://github.com/mustache/spec. It's in the "spec-compliant" branch. I've been playing with this a little but have yet to look at that entire branch properly to see what state it's in. Also, I've not looked at how far, and to what degree the current state of pystache is spec compliant. It might be nice to have these tests in the development branch to make it easier to test pull requests for regressions.

**Comment by carlmw** [comment]
We're currently planning to bring pystache in line with the spec by building on my colleague @dgym's work on cystache (https://github.com/dgym/cystache). If you're looking for fast a implementation I'd look there. It doesn't suffer from the tight coupling with View and generally rocks. Going forward I see pystache building that work.

**Comment by pvande** [comment]
I did a spec-compatible tweak to pystache based on [Milk](https://github.com/pvande/Milk)'s (_very fast!_) parser in my fork a while ago (https://github.com/pvande/pystache).  I never submitted it as a pull request, because I couldn't quite get the Pythonic feel in place, and it felt like hacking the right thing into the wrong API.  It's still worth taking a look at, in part because [the spec examples are first-class tests](https://github.com/pvande/pystache/blob/master/tests/test_spec.py).  

Also, it's probably worth reading through [Milk's implementation](http://pvande.github.com/Milk); it's fairly heavily annotated, and fairly simple overall.)

**Comment by carlmw** [comment]
@pvande the spec-compliant branch was my attempt to bring your fork in (nice job btw). I think that finishing that off would solve a lot of the outstanding issues. I left it in a separate branch because I figured that it would break compatibility with the current implementation (there are a few quirks).

There are currently 14 failures in the spec-compliant branch. If we can nail these I think we'll be in pretty good shape.

**Comment by cjerdonek** [comment]
Are those who would like to participate as maintainers okay with @io41's suggestion to use the mailing list he created for discussion?  I posted a message there, but no one responded.  I don't have a strong preference, but I think being on the same page would help.

Incidentally, does the GitHub UI not allow people who haven't been added as collaborators to see the list of collaborators for a project?  I haven't been added yet, so I'm not seeing that information (or maybe I'm looking in the wrong place).

**Comment by cjerdonek** [comment]
I'm curious about something.  What's the reason for the apparent discrepancy between @carlmw saying above that there are 14 failures in the spec-compliant branch, and @pvande saying in [this commit](https://github.com/defunkt/pystache/commit/e06bed513dd380bb7760a2bf69af2f7bc0edf405) (which was merged into spec-compliant) that the code is "compatible with Mustache spec v1.0.3."  Is that because the failures occur in newer versions of the spec, or because failures were introduced in the merge process?

**Comment by cjerdonek** [comment]
I'm closing this issue as @pvande's code has been merged into the development branch as of today, and because this repo is now being maintained.

I will also be deleting the spec-compliant branch in the next few days since @pvande's code in that branch has been merged with all tests passing.
