### ISSUE TITLE
Quotes are not escaped

### ISSUE THREAD

**Issue by phihag** [defunkt/pystache#79]
This may be an error in mustache, or a misconception of mine, but why are quotes (in attribute values, but optionally everywhere else too) not escaped?

```
>>> import pystache
>>> pystache.render(u'<div title="{{title}}">Hover</div>', {'title': u'The "mustache" library'})
u'<div title="The "mustache" library">Hover</div>'
```

I expected

```
u'<div title="The &quot;mustache&quot; library">Hover</div>'
```

which matches the output (sans `u`, of course) I get from [mustache.js](https://github.com/janl/mustache.js).

**Comment by cjerdonek** [comment]
Thanks for the report.  This is a known issue (issue #67) that has been fixed in the development branch.  Hopefully we'll be [releasing that](https://github.com/defunkt/pystache/issues/77) in the not-too-distant future.  In the meantime, if you're using what's in master, I believe things should work as you expect if you install [markupsafe](http://pypi.python.org/pypi/MarkupSafe) (the version in master uses markupsafe's escape if markupsafe is available).

**Comment by phihag** [comment]
Since I modify pystache anyways (to get it running under Python 3), I just patched in the fix:

```
diff --git a/pystache/template.py b/pystache/template.py
index 563d830..a5ee092 100644
--- a/pystache/template.py
+++ b/pystache/template.py
@@ -13 +13 @@ except ImportError:
-    escape = lambda x: cgi.escape(unicode(x))
+    escape = lambda x: cgi.escape(unicode(x), quote=True)
```

With this change, quotes are correctly escaped.

**Comment by cjerdonek** [comment]
Great!

**Comment by cjerdonek** [comment]
FYI, I'm just about to release a new version of Pystache (v0.5.1, just [pushed](https://github.com/defunkt/pystache/commit/b5a688920af19f74be8189150f4b8b7e27d9f416) to master) with official support for Python 3.  If you're still using Pystache, I'd love for you to try it out.
